CC = gcc
CFLAGS = -ggdb -pedantic -Wall -Wextra -Wpedantic
LFLAGS =
TARGET = $(c_filename)
#filename without extension
# all: $(TARGET)
# 	$(TARGET): $(TARGET).c : $(CC) $(CFLAGS) -o $(TARGET) $(TARGET).c $(LFLAGS)
all: $(TARGET)
	$(CC) $(CFLAGS) -o $(TARGET) $(TARGET).c $(LFLAGS)
